### ISSUE TITLE
Gem Tree Harvester receives too much loot after running for a while

### ISSUE THREAD

**Issue by TheBrutalSkull** [Crackminer/miningcracks_take_on_luiafk#15]
Putting this here, but we should be fine in a few tries. We're on it

**Comment by TheBrutalSkull** [comment]
Put the gemcorn in the chest for now

**Comment by Crackminer** [comment]
can now replant but its only topaz right now

**Comment by TheBrutalSkull** [comment]
Bug in multiplayer : sappling are not "visually" there, but if relog, they are, so it's a netmessage issue probably. 
We need to replace the harvester everytimes after a relog into the world.

**Comment by TheBrutalSkull** [comment]
Sappling is visible, but appears like topaz, It grows the right gem tree
Drop amounts for gemcorn tree harvester is not right
Again, we need to fix the fact that we need to replace the harvester, it's all the harvester, not just the gemcorn

**Comment by Crackminer** [comment]
only bug left is gemcorn harvester receiving too much loot after a while in servers (Host and Play, Dedicated). Singleplayer is fine

**Comment by TheBrutalSkull** [comment]
Working perfectly fine for now.
