### ISSUE TITLE
Multiplayer silent exceptions

### ISSUE THREAD

**Issue by Crackminer** [Crackminer/miningcracks_take_on_luiafk#18]
From user: https://steamcommunity.com/profiles/76561198079909385

Just wanted to let you know that in multiplayer this mod is creating an error that causes me and my friends to run at 30 fps with constant 5-7 fps drops. After 12 hours of troubleshooting, I checked the server log (should have done it first) and I noticed it was creating some kind of exception error? Idk much about that stuff. Hopefully this can be fixed or was just on my end. Just for the sake of information, I'm running on a BEEFY pc, with gigabit.

also have frame skip turned off, if that helps lol

**Comment by Crackminer** [comment]
I will try to get him to tell me the mods he uses, as well as trying to get a copy of the world and the players if possible

**Comment by TheBrutalSkull** [comment]
Maybe get the client.log and the server.log aswell

**Comment by Crackminer** [comment]
assuming it was the exception of luiafkplayer.cs line 237: fixed

**Comment by TheBrutalSkull** [comment]
We assumed it's fixed
